### PR TITLE
add: `ubuntu-mate-welcome`

### PR DESCRIPTION
**Pull request by X4X5**
This adds the Ubuntu MATE welcome screen to `MATE (Ubuntu)`. This is a snap dependency, so if this gets merged, I'll update the rhino-deinst wiki accordingly

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
What if snaps are removed by rhino-config?

**Comment by X4X5** [comment]
Huh. I'll fix that.

**Comment by X4X5** [comment]
I added `sudo apt-get install snapd -y` under the line I created, in the case that the user uninstalls snapd.

**Comment by cat-master21** [comment]
Well what if users don't want snap and they hold snap to not install too?

**Comment by X4X5** [comment]
I think at that point, it would skip that part of installation. If you have a way to propose that we make sure the instruction does get skipped if snap is held, then please let me know. I also did the same thing to Ubuntu Budgie in my [previous PR](#24).

The reason these two snaps are getting installed is because part of the experience of Ubuntu Budgie and Ubuntu MATE is the layouts themes, artistic themes, ect. There are deb packages of them, but when I tried that, both Budgie and MATE welcome apps uninstalled themselves and installed the snap variants.

**Comment by Elsie19** [comment]
I'm closing this as snaps are not usually guaranteed or wanted on the system. I prefer for rhino-deinst to use only debs, as that's what we can guarantee to be installed on a system (apt)

**Pull request closed without merging**
